### ISSUE TITLE
Error: no such command: 'snippets-menu' when running inside tmux

### ISSUE THREAD

**Issue by sucrecacao** [alexherbo2/snippets.kak#10]
When running my kak inside tmux ( `tmux new-session kak` ) and type `<a-enter>` in insert mode I get the following error:
`Error: no such command: 'snippets-menu'`

**Comment by alexherbo2** [comment]
I have no idea.

**Comment by alexherbo2** [comment]
@sucrecacao The menu has been removed and we use completers now.
