### ISSUE TITLE
Document usage a bit better

### ISSUE THREAD

**Issue by winged** [alexherbo2/snippets.kak#6]
Hi,

I really like your plugins! And especially snippets.kak would be very very useful. However, I think the README could use some love:

* How exactly do I trigger snippet expansion?
* How do we write snippets?

I'd gladly help expanding the docs, but first I'd have to understand how it's supposed to work (and why it's doing things the way it does, for example why do I need to write the snippet in brackets?)

**Comment by alexherbo2** [comment]
Hi @winged,

Currently, for the simplicity of implementation.  We have the exact key to query a snippet.
I wanted to start with a simple implementation, so we can add the detection on top.

I would like to see a better documentation too, especially for [Rails].
But I wait to do some Rails before adding them.

[Rails]: https://rubyonrails.org
