### ISSUE TITLE
How to actually expand snippets?

### ISSUE THREAD

**Issue by alecStewart1** [alexherbo2/snippets.kak#7]
So I'm not entirely clear how I'm to expand snippets.

I understand `<a-ret>` is supposed to expand a snippet, but it doesn't.

In just a file called `test.sh` I typed `if` and then pressed `<a-ret>`. Nothing happened but I got:

```
Error: 1:2: 'type-expand-command' 2:5: 'execute-keys' no selections remaining
```

Ok, so I assume I have to select the snippet? I go back to normal mode and select the snippet with `x` and press `<a-ret>`. Same error as above. 

I go to insert mode keeping the selection and press `<a-ret>`. Same error.

What am I missing?

EDIT: well I ran the command `snippets-enable`, and then selected the "if" and manually ran `snippets-expand-selection` and got

```
Error: No such snippet: sh/if␊ global/if␊ in /home/bigdaddy/.config/kak/snippets /home/bigdaddy/.config/kak/plugins/snippets.kak/snippets /home/bigdaddy/.config/kak/plugins/kakoune-snippet-collection/snippets
```

But...it's [there](https://github.com/alexherbo2/snippets.kak/blob/master/snippets/sh/if#L1).

**Comment by alexherbo2** [comment]
You have to run the command in a matching pair, with [prelude.kak] and [type-expand.kak] installed.

```
(lorem-ipsum<a-ret>)
```

[prelude.kak]: https://github.com/alexherbo2/prelude.kak
[type-expand.kak]: https://github.com/alexherbo2/type-expand.kak

It is done that way for the simplicity of the implementation, but it is not ideal for use.

**Comment by alecStewart1** [comment]
Ahh. The matching pair part is what I was missing.

**Comment by sucrecacao** [comment]
yes I was missing that part too. Its not clear in the readme
